#+ method: GET
#+ summary: Query that retrieves all existing executions and whether they are successful or not

PREFIX opmw: <http://www.opmw.org/ontology/>

SELECT distinct ?execution ?status from <urn:x-arq:UnionGraph>
WHERE {
  ?execution a opmw:WorkflowExecutionAccount;
      opmw:hasStatus ?status.  
}
